register_repository(
  NAME
    hdrhistogram
  REPOSITORY
    HdrHistogram/HdrHistogram_c
  COMMIT
    8885476fc83fa362fec2fb2b5e9cd9544514976e
)

register_cmake_command(
  TARGET
    hdrhistogram
  LIBRARIES
    hdr_histogram_static
  INCLUDES
    include
  LIB_PATH
    src
  ARGS
    -DHDR_HISTOGRAM_BUILD_SHARED=OFF
    -DHDR_HISTOGRAM_BUILD_STATIC=ON
    -DHDR_LOG_REQUIRED=DISABLED
    -DHDR_HISTOGRAM_BUILD_PROGRAMS=OFF
)