register_repository(
  NAME
    hdrhistogram
  REPOSITORY
    HdrHistogram/HdrHistogram_c
  COMMIT
    18c7a324383dded1451d15621cd018b0048057d0
)

register_cmake_command(
  TARGET
    hdrhistogram
  LIBRARIES
    hdr_histogram_static
  INCLUDES
    include
  LIB_PATH
    src
  ARGS
    -DHDR_HISTOGRAM_BUILD_SHARED=OFF
    -DHDR_HISTOGRAM_BUILD_STATIC=ON
    -DHDR_LOG_REQUIRED=DISABLED
    -DHDR_HISTOGRAM_BUILD_PROGRAMS=OFF
)